export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  GROUP_FULL: 'GROUP_FULL',
  RATE_LIMITED: 'RATE_LIMITED',
  STORAGE_EXCEEDED: 'STORAGE_EXCEEDED',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_INVALID: 'INVITE_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
